---
title: "Useful tools and platforms for Data Management"
---

## To be part of an assembly

* [Authentik](https://goauthentik.io/) is a central authority provider.

[Docker and Kubernetes installations](https://docs.goauthentik.io/docs/installation/)

* [Keycloak, Open Source Identity and Access Management](https://www.keycloak.org/)

[Docker and Kubernetes installations](https://www.keycloak.org/guides#getting-started)

* [Authelia, an open-source authentication and authorization server](https://www.authelia.com/)

[Docker and Kubernetes installations](https://www.authelia.com/integration/deployment/introduction/)

* [MinIO, a S3 compatible high performance object store](https://github.com/minio/minio)

Containerization via PodMan, not production.

* [Apache Spark, engine for large-scale analytics](https://spark.apache.org/)

A commonly used engine for storing and analysing Scientific data.

[Kubernetes installations](https://spark.apache.org/docs/latest/running-on-kubernetes.html)

* [RDF, "The Resource Description Framework (RDF) is a general framework for representing interconnected data on the web"](https://www.w3.org/RDF/)

## As extra of a solution or an assembly

* [Heimdall](https://heimdall.site/) is a web-application that provide a dashboard on other web-applications

[Docker installation](https://hub.docker.com/r/linuxserver/heimdall/)

* [GreyLog, centralized log management application](https://graylog.org/)

[Docker and docker-compose installations](https://graylog.org/downloads/)

* [Grafana, Grafana is a multi-platform open source analytics and interactive visualization web application. It can produce charts, graphs, and alerts for the web when connected to supported data sources (wikipedia)](https://grafana.com/)

With installation with [docker, docker-compose, kubernetes and helm charts](https://grafana.com/docs/grafana/latest/setup-grafana/installation/)

## For tutorials

Documentations systems

* [JupyterLab, "web-based interactive development environment for notebooks, code, and data"](https://jupyter.org/)

[Installation of Jupyter Hub (multi-user) on Kubernetes](https://z2jh.jupyter.org/en/stable/)

* [Collab is a Google-hosted Jupyter Notebook service, useful for online tutorials](https://colab.google/)

* [WebTop, "Alpine, Ubuntu, Fedora, and Arch based containers containing full desktop environments in officially supported flavors accessible via any modern web browser."](https://github.com/linuxserver/docker-webtop)
    + [Docker and docker-compose installations](https://github.com/linuxserver/docker-webtop?tab=readme-ov-file#usage)

* [Quarto, used for this website, "An open-source scientific and technical publishing system"](https://quarto.org/)
    + Available as standalone, but also as extension for text editors and github action for rendering [GitHub pages](https://quarto.org/docs/publishing/github-pages.html)