---
title: "De.KCD - Major Data Management platforms - Draft"
---

## FAIR - **F**indable, **A**ccessible, **I**nteroperable, **R**eusable

The Data Management platforms listed should respect the FAIR principle to some extend. The details follow this idea: if a platform offers an extensive API but it is very difficult to find a documentation, then it is not findable or accessible, thus should be considered as such.
On the other hand, a platform based on common standards such as RDF or Apache Spark might be interoperable and reusable without needing to document RDF or Apache Spark as their documentation are easily available.

## Contributions are welcome

Feel free to contribute by forking the repository or creating an issue.
We filled the information by the best of our knowlegde and after a reasonable amount of research, but that does not prevent us from doing mistakes. Once again we will be glad for any correction.

## Progress

* TODO: Analysis of combinability, transferability to other domains and their adaptability to cloud architectures.
The first step is to complete a dry list of solution with their adaptability to cloud architecture (mostly if they have a containerization set-up).

* Incomplete: astronomy. 

## Process

Top-Down approach: first listing with technical information (online, containers, ...), then API support. Finally interoperability (data format of API), possibility of transfer to other domains and adaptability to cloud.
Major platforms are easy-to-find and popular platforms.
Draft should be in to_sort or to_investigate pages.

The format is keep as simple as possible so it is easier to modify. We find it more important to encourage contributions as to keep the list up-to-date. This is why we don't use tables for instance. 

## To Work-On

* Write about non-software dedicated DM approach (for instance semantic-web, RDF or Apache Spark).

* Better presentation, without making editing more complex

* How to present transferability

## Life Science

### Open Source or free

* [Galaxy, an web-based platform for biomedical research, allowing cloud-based workflows](https://usegalaxy.org/)
    + Galaxy is already a cloud-based solution, widely used.
    + It is a very powerful tool and as such with [tutorials](https://training.galaxyproject.org/), [documentation](https://galaxyproject.org/get-started/), [training events](https://training.galaxyproject.org/training-material/events/index.html), [faqs](https://training.galaxyproject.org/training-material/faqs/) and [discussions](https://help.galaxyproject.org/)
    + [Extensive API](https://training.galaxyproject.org/training-material/api/)
    + Interoperability **HIGH**: uses well-documented JSON.
    + **Mostly** cross-domain: though mostly for life-science applications, it can support any kind of workflow. Tools for other domains can be added.

* [BioContainers, "community-driven project to create and manage bioinformatics software containers"](https://biocontainers.pro/)
    + Tools to create container and registry of created containers
    + [API](https://api.biocontainers.pro/ga4gh/trs/v2/ui/)
    + Interoperability **HIGH**: made for helping other tools being more interoperable
    + **Mostly** cross-domain: the registry is for bioinformatics software only but some tools, mostly [Mulled](https://github.com/BioContainers/mulled) can be used in any domain.

* [Omero, an open source imaging platform for microscopy outputs](https://www.openmicroscopy.org/omero/)
    + [Docker Image](https://hub.docker.com/r/openmicroscopy/omero-web-standalone) and [Helm chart](https://github.com/manics/kubernetes-omero)
    + [Extensive API](https://omero.readthedocs.io/en/v5.6.13/developers/json-api.html)
    + Interoperability **HIGH**: uses well-documented JSON.
    + **Mostly** cross-domain: despite being targeted at microscopy image, can have an use for any image data management. Omero can be extended using [OMERO.scripts](https://omero.readthedocs.io/en/v5.6.13/developers/scripts/index.html) which are written in MATLAB or Python. It also offers binding in Python, C++, MATLAB and Java.

* [Seek](https://seek4science.org/)
    + [Docker Compose(one instance on one server!)](https://docs.seek4science.org/tech/docker/docker-compose.html)
    + [Extensive API](https://docs.seek4science.org/help/user-guide/api.html)
    + Interoperability **HIGH**: uses well-documented JSON.
    + **Mostly** cross-domain: Seek is highly configurable and could be used as a sharing platform for other domains, without any coding needs.
        - Related: [Just Enough Results Model (JERM)](https://jermontology.org/)

* [Aruna Object Storage (AOS)](https://aruna-storage.org/)
    + "Aruna Object Storage (AOS) is a modern distributed storage platform designed to meet the increasing demand for effective data management and storage of scientific data. It is the central storage of the Research Data Commons (RDC) cloud layer and the data foundation for the upper layers. It is a cloud-native, scalable system with an API and a S3-compatible interface."
    + Online but provide a [Docker Compose installation](https://github.com/ArunaStorage/aruna?tab=readme-ov-file#getting-started)
    + [Extensive API](https://github.com/ArunaStorage/api)
    + Interoperability **HIGH**: well documented, uses protocol-buffers and the gRPC framework and exposes the S3 API .
    + **Fully** cross-domain: can be used for any kind of storage.

* [XNAT](https://www.xnat.org/)
    + XNAT is an open source imaging informatics platform, mostly for MRT/CT Scan images (DICOM & NIfTI). [Presentation on usage](https://tu-dresden.de/bereichsuebergreifendes/nic/ressourcen/dateien/nic-data-management/2020-12-10_Neukam_X-Nat-Data-Management.pdf?lang=de)
    + [Docker Compose installation](https://www.xnat.org/download/), [Docker Compose](https://github.com/NrgXnat/xnat-docker-compose)
    + [Extensive API](https://wiki.xnat.org/xnat-api/xnat-rest-api-directory)
    + Interoperability **HIGH**: uses well-documented JSON.
    + **Not** cross-domain: it is a highly specialised and complex tool and would not be adapted for other applications. In the medical domain, support many applications via [plugins](https://marketplace.xnat.org/plugins/)

* [REDCap – Research Electronic Data Capture](https://www.project-redcap.org/)
    + Free for non-profit institutions but not Open Source, available upon request.
    + No containerization.
    + Extensive API, but most documentation is for registered members.
    + Interoperability **unknown but presumably high/medium**.
    + **Probably not** cross-domain: software adaptation is limited to built-in software development tools. There is no public documentation.

* [ISA format, set of formats and related tools for bioscience experiment](http://isa-tools.org)
    + Standalone tools that could be containerized with a little technical effort.
    + Formats and tools are well-documented
    + Interoperability **high**: well-documented workflow (https://isa-tools.org/software-suite.html), all format explained.
    + **Mostly not** cross-domain: these are dedicated tools for biosciense. However everything is open-source and could be used as base for other tools.

* ["LifeMonitor is a service to support the sustainability and reusability of published computational workflows"](https://crs4.github.io/life_monitor/)
    + A github app for workflows hosted on GitHub, also with [docker-compose installation](https://github.com/crs4/life_monitor?tab=readme-ov-file#getting-started)
    + [Extensive API, well documented](https://api.lifemonitor.eu/static/specs/apidocs.html#overview)
    + Interoperability **high**: uses well-documented JSON.
    + **Mostly not** cross-domain: it could be used to test different domains' workflow, but it does not seem to be obvious.

* [Workflow Hub, registry for describing, sharing and publishing scientific computational workflow](https://about.workflowhub.eu/)
    + Online, based on Seek
    + [Extensive API, well documented](https://about.workflowhub.eu/developer/)
    + Interoperability **high**: uses well-documented JSON.
    + **Fully** cross-domain: "WorkflowHub is a domain-agnostic workflow registry designed around FAIR principles."

* [BioModels, a repository of mathematical models of biological and biomedical systems](https://www.ebi.ac.uk/biomodels/)
    + Online only.
    + [Extensive APIs](https://www.ebi.ac.uk/biomodels/dev)
    + Interoperability **high**: uses well-documented JSON or XML.
    + **Not** cross-domain: by definition

### Commercials

* [Oracle Clinical, an Electronic Health Record and Data Management platform](https://www.oracle.com/life-sciences/clinical-trials/)
    + No easily findable public documentation
    + **Not** cross-domain

* [MediData, a set of platforms for clinical trials, Electronic Health Record and Data management](https://www.medidata.com)
    + No easily findable public documentation
    + **Not** cross-domain

* [Castor, Electronic Health Record](https://www.castoredc.com/electronic-data-capture-system/)
    + [Extensive API, well documented](https://data.castoredc.com/api)
    + Interoperability **high**: uses well-documented JSON.
    + **Not** cross-domain

## Pharmaceutics

* [LabKey, an open-source platform that helps manage biomedical research data, focusing on clinical and laboratory data](https://www.labkey.org)
    + A limited free edition and several paid versions,
    + [Extensive APIs, well documented](https://www.labkey.org/Documentation/wiki-page.view?name=viewApis)
    + Interoperability **medium/high**: APIs are well-documented but are programmatic only (i.e no REST API)
    + **Moderately cross-domain**: while many function could be used for other domain, it is mostly dedicated to biomedical research.

* [CIViC (Clinical Interpretation of Variants in Cancer), an open-access platform that curates and manages clinical cancer variant data. It is used for pharmaceutical oncology research.](https://civicdb.org)
    + Mostly online, fully Open Source, no containerization.
    + [Extensive API, well documented](https://griffithlab.github.io/civic-v2/)
    + Interoperability **high**: uses well-documented JSON.
    + **Not** cross-domain: it is a highly specialised and complex tool and would not be adapted for other applications

## Materials science

* [NOMAD, management and sharing of material science data (online)](https://nomad-lab.eu/nomad-lab/)
    + With many [tutorials](https://www.fairmat-nfdi.eu/fairmat/outreach-fairmat/tutorials-fairmat), also on [Youtube](https://www.youtube.com/watch?v=FqTTeAgqiuw)
    + Online first, but with [docker compose installation](https://nomad-lab.eu/prod/v1/docs/howto/oasis/install.html). Another instance of NOMAD, called NOMAD Oasis, can upload to the central NOMAD installation.
    + [Extensive API, well documented](https://nomad-lab.eu/prod/v1/docs/howto/programmatic/api.html)
    + Interoperability **HIGH**: uses well-documented JSON.
    + **Not** cross-domain: it is a highly specialised and complex tool and would not be adapted for other applications.


* [pyiron, complex workflow made based on JupiterLab](https://pyiron.org/) and [pyiron workflow](https://github.com/pyiron/pyiron_workflow) with many [extensions](https://github.com/pyiron)
    + With a set of [docker images](https://github.com/pyiron/docker-stacks)
    + Based on JupiterLab, supporting a [command-line interface](https://pyiron.readthedocs.io/en/latest/source/commandline.html) that can be easily extended, and well documented.
    + Interoperability **HIGH**: standard JupiterLab capabililities, all documented.
    + **Fully** cross-domain: even if dedicated to material science, its integration to JupiterLab makes using any part usable in other domains.

* [HELIPORT (HElmholtz ScIentific Project WORkflow PlaTform)— An Integrated Research Data Lifecycle](https://heliport.hzdr.de/)
    + No container-based installation. Mosty online versions, restricted to members of Helmhotz or associated institutions.
    + Extensive API and extensions support.
    + Interoperability **HIGH**: uses well-documented JSON.
    + **Fully** cross-domain: already extended for other uses. But the online versions are currently restricted to members of Helmhotz or associated institutions.

## Geomatics

### Open Source

* [GeoServer, "an open source server for sharing geospatial data"](https://geoserver.org/)
    + No container-based installation.
    + [Extensive API](https://docs.geoserver.org/latest/en/user/) and many extensions, well documented.
    + Interoperability **HIGH**: support many common formats, well documented.
    + **Mostly** cross-domain: it is dedicated to geospatial data but could be use for any domain as such. 

* [MapGuide Open Source, " a web-based platform that enables users to develop and deploy web mapping applications and geospatial web services."](https://www.osgeo.org/projects/mapguide-open-source/) and [MapServer, a mapping engine](https://mapserver.org/), part of a large portofolio of [Geospatial tools](https://www.osgeo.org/)
    + No container-based installation.
    + Extensive API via the related tools.
    + Interoperability **HIGH**: support many common formats, documented. One issue of the OSGeo portfolio is the high number of projects with many subpages. As such the contribution to the community is very high, but it can be difficult to navigate. 
    + **Mostly** cross-domain: it is dedicated to geospatial data but could be use for any domain as such. 

* [Mapnik, open-source mapping toolkit](https://mapnik.org/)
    + No container-based installation as it is a toolkit to develop mapping applications.
    + Mostly to be used as an API or through Python bindings. It is largely [documented](https://github.com/mapnik/mapnik/wiki/LearningMapnik) but mostly aimed as developers.
    Interoperability **MEDIUM/HIGH**: it is aimed at helping develop any kind of mapping applications, but will probably be out of reach as such for non-developers.
    + **Mostly** cross-domain: it is dedicated to geospatial data but could be use for any domain as such. 

* [ArangoDB, open-source and commercial graph and spatial database](https://arangodb.com/), community version limited to 100gb of data on a single cluster and non-commercial use.
    + [Docker and Kubernetes installations](https://arangodb.com/download-major/)
    + [Extensive API, well documented, also built-in using Swagger.IO](https://docs.arangodb.com/stable/develop/http-api/#restful-api)
    + Interoperability **HIGH**: it is all well-documented and uses JSON. 
    + **Fully** cross-domain: it is a general multi-model database

* [GeoNetwork, catalog application to manage spatially referenced resources](https://geonetwork-opensource.org/)
    + [Docker image](https://docs.geonetwork-opensource.org/4.4/install-guide/installing-with-docker/)
    + [Extensive API, well documented](https://docs.geonetwork-opensource.org/4.4/api/)
    + Interoperability **HIGH**: uses well-documented JSON.
    + **Mostly** cross-domain: it is dedicated to geospatial data but could be use for any domain as such. 

* [GeoNode, an open-source platform for geospatial data sharing, often used for urban planning. It integrates tools for geographic data visualization, editing, and management](https://geonode.org)
    + [Docker-based installation](https://docs.geonode.org/en/master/install/basic/index.html)
    + [Extensive API, very well documented](https://docs.geonode.org/en/master/devel/index.html)
    + Interoperability **HIGH**: uses well-documented JSON.
    + **Mostly** cross-domain: it is dedicated to geospatial data but could be use for any domain as such. 

* [OpenStreetMap (OSM), a collaborative project to create a free, editable map of the world, providing spatial data for urban planning, navigation, and research](https://www.openstreetmap.org) 
    + Mostly online with the map of the full world, with many surrounding tools
    + [Extensive API, very well documented](https://wiki.openstreetmap.org/wiki/API)
    + Interoperability **HIGH**: uses well-documented XML, JSON. Maps are either using a text-based format, giving a large size but easy to use, such as [OSM XML](https://wiki.openstreetmap.org/wiki/OSM_XML) or a binary format such as [PBF](https://wiki.openstreetmap.org/wiki/PBF_Format), giving a small size but harder to use. The list of map format is on the [wiki](https://wiki.openstreetmap.org/wiki/Category:OSM_file_formats)
    + **Mostly** cross-domain: it can be use for any domain. Its usage can be quite complex though, depending on several aspects: extracting a small map can be rather easy using one tool, extracting a large map (such as for a country) can be complex depending on the level of detail needed. The binary format for large map

### Commercials

* [ESRI ArcGIS, geospatial platform](https://www.esri.com/en-us/arcgis/geospatial-platform/overview)
    + Many [tutorials](https://learn.arcgis.com/en/gallery/) which are rather hard to navigate and an [extensive developer documentation](https://developers.arcgis.com/documentation/), not linked on the product page.
    + [Extensive APIs, well documented](https://developers.arcgis.com/documentation/) with many [Open Source tools and samples](https://esri.github.io/)
    + Interoperability **HIGH**: many APIs and tools, with documentation and samples.   
    + **Mostly** cross-domain: it is dedicated to geospatial data but could be use for any domain as such. 

* [SMARTGeo, visualization and analytics platform](https://smartgeo.io/)
    + No easily findable public documentation
    + **Mostly** cross-domain: it is dedicated to geospatial data but could be use for any domain as such. 

* [CARTO, cloud-based spatial analysis](https://carto.com/)
    + [All documentation is available publicly](https://docs.carto.com/) with a [set of tutorials covering the bases of geospatial data as well](https://academy.carto.com/)
    + Offer [several possibilities of connections, all documented](https://docs.carto.com/carto-user-manual/connections) and several [well documented APIs](https://docs.carto.com/carto-for-developers/key-concepts/apis).
    + Interoperability **HIGH**: APIs uses well-documented JSON
    + **Mostly** cross-domain: it is dedicated to geospatial data but could be use for any domain as such. 


## Urbanism

### Open Source or free

* [Metropolis (Urban Observatory Data), offers large-scale urban data and insights about cities, covering everything from mobility patterns to energy consumption](https://use.metropolis.org)
    + Online collection of urban case studies.
    + No API
    + No interoperability, per definition
    + **Partly** cross-domain: as the case studies are about urbanism with themes which can be relevant for other domains.

* [CitySDK, a toolkit offering standard API specifications for urban services, helping cities release open data and enabling developers to create city-related applications](http://www.citysdk.eu)
    + SDK to build Smart City services and applications,
    + Encourages to build a [standardised API, using JSON, XML or CSV](https://www.citysdk.eu/wp-content/uploads/2017/11/20171116_APIrecommendations_WEB.pdf)
    + Interoperability **HIGH**: encourages the use of [standards](https://www.citysdk.eu/citysdk-toolkit/components-of-the-toolkit/)
    + **Mostly** cross-domain: it should to be used for city management, but does not restrict on any use.

### Commercials

* [ESRI ArcGIS Urban](https://urban.arcgis.com/)
    + ArcGIS Urban is part of the ArcGIS portfolio, so have the same characteristics.
    + Many [tutorials](https://learn.arcgis.com/en/gallery/) which are rather hard to navigate and an [extensive developer documentation](https://developers.arcgis.com/documentation/), not linked on the product page.
    + [Extensive APIs, well documented](https://developers.arcgis.com/documentation/) with many [Open Source tools and samples](https://esri.github.io/)
    + Interoperability **HIGH**: many APIs and tools, with documentation and samples.
    + **Mostly** cross-domain, it is dedicated to geospatial data but could be use for any domain as such. 

* [Google Transit, provides data on urban transport, such as real-time traffic, transit options, and pedestrian data, used in urban planning and mobility solutions](https://developers.google.com/transit)
    + it is an online feed using the GTFS format with some [documented changes for the realtime transit](https://developers.google.com/transit/gtfs-realtime/reference).
    + Interoperability **HIGH**: straightforward and well documented
    + **Not** cross-domain, as per definition.


## Digital Lab Notebooks

* [OpenBis](https://openbis.ch/)
    + [Docker image](https://unlimited.ethz.ch/display/openbis/openBIS+Download+Page)
    + [Extensive APIs, well documented](https://openbis.readthedocs.io/en/20.10.x/software-developer-documentation/apis/index.html)
    + Interoperability **HIGH**: while there is no REST APIs, the other APIs are well documented and the Python API is simple to use even for non-developers.
    + **Fully** cross-domain: OpenBis is highly configurable so can be use for any domain as a notebook but can also be used for other needs if properly configured. Then it is not the easiest platform to set-up and configure.

* [eLabFTW](https://www.elabftw.net/)
    + [Docker](https://doc.elabftw.net/install.html)
    + [Extensive APIs, well documented](https://doc.elabftw.net/api.html)
    + Interoperability **HIGH**: the REST API uses well-documented JSON and the Python API offers plenty of examples.
    + **Fully** cross-domain: eLabFTW is highly configurable so can be use for any domain as a notebook but can also be used for other needs if properly configured.

* [RSpace, electronic noteboook and inventory management](https://www.researchspace.com/)
    + Open Source and commercial solutions.
    + [Docker Compose](https://github.com/rspace-os/rspace-docker)
    + [Extensive API and SDK, well documented](https://documentation.researchspace.com/category/ifpi5pwbck-for-developers).
    + Interoperability **HIGH**: uses well-documented JSON.
    + **Fully** cross-domain: eLabFTW is highly configurable so can be use for any domain as a notebook but can also be used for other needs if properly configured.

## Astronomy

Astronomy is largely standardized and relies on many tools developed over several decades, and online catalogues. As such many are standalone tools and are potentially cloud-friendly, though will need some more technical adaptations. Most platforms are not cross-domain are they give data from astronomical observations. But as such, if there is an actual need for such data in another domain, the technical effort for the integration will probably be worth it. The technical effort changes greatly between platform and can be rather high with many specialised tools and specialised vocabulary.

* [Virtual Observatory (VO), the International Virtual Observatory Alliance (IVOA) provides resources for discovering and accessing astronomical data, including standards for data sharing and interoperability](https://www.ivoa.net/)
    + Online only
    + Many tools but no clear or official API.
    + Interoperability **LOW**: related to previous point.
    + **Not** cross-domain, per definition.

* [ALMA Science Archive, the ALMA archive gives access to data from the Atacama Large Millimeter/submillimeter Array, providing public access to radio astronomy dataset](https://almascience.nrao.edu/aq/)
    + Online only
    + Many tools and documentations but it is also difficult to find an official API
    + Interoperability **LOW**: related to previous point.
    + **Not** cross-domain, per definition. 

* [European Space Agency (ESA) Archives, ESA’s space science archives, including data from missions like Gaia and Hubble, offering open access to space mission data](https://www.cosmos.esa.int/web/esdc)
    + Online only,
    + Some archives have an API access, such as the [herschel science archive](http://archives.esac.esa.int/hsa/whsa/), but it is not uniform.
    + Interoperability **LOW to HIGH**: related to previous point, depending on the archive.
    + **Not** cross-domain, per definition.

* [NASA’s Astrophysics Data System (ADS), ADS is a digital library for astronomy and physics, linking research papers with relevant datasets and providing extensive search capabilities](https://ui.adsabs.harvard.edu/)
    + Online only,
    + [Extensive API, well documented with examples](https://ui.adsabs.harvard.edu/help/api/)
    + Interoperability **HIGH**: uses well-documented JSON.
    + **Mostly** cross-domain: some papers referenced are cross-domain or in another domain.

* [SIMBAD (Set of Identifications, Measurements, and Bibliography for Astronomical Data), SIMBAD is a database providing detailed records of celestial objects and their bibliographical references](http://simbad.u-strasbg.fr/simbad/)
    + Online only,
    + [API, documented](http://simbad.cds.unistra.fr/guide/sim-url.htx)
    + Interoperability **MEDIUM/HIGH**: the API needs some technical understanding of the domain to be of use.
    + **Not** cross-domain, per definition.

* [SkyServer (Sloan Digital Sky Survey, SDSS), SkyServer provides access to data from the Sloan Digital Sky Survey, with resources for professional astronomers and public users](http://skyserver.sdss.org/)
    + Online only,
    + [Extensive APi, well documented](https://skyserver.sdss.org/dr18/Support/Api). Also propose a nice [SQL tutorial](https://skyserver.sdss.org/dr16/en/help/howto/search/searchhowtohome.aspx) 
    + Interoperability **HIGH**: well-documented API, simple to use,
    + **Not** cross-domain, per definition.

* [TESS Data Portal, the TESS Data Portal provides access to data from the Transiting Exoplanet Survey Satellite, focusing on exoplanet discovery](https://archive.stsci.edu/missions-and-data/tess)
    + Online only,
    + [API, documented](https://astroquery.readthedocs.io/en/latest/mast/mast.html)
    + Interoperability **MEDIUM/HIGH**: the API needs some technical understanding of the domain to be of use.
    + **Not** cross-domain, per definition.

* [ESO Science Archive Facility, the European Southern Observatory (ESO) archive contains data from its observatories, including the Very Large Telescope (VLT), and provides tools for data retrieval and analysis](http://archive.eso.org/)
    + Online only,
    + [API, documented](http://archive.eso.org/programmatic/)
    Interoperability **MEDIUM/HIGH**: the API needs some technical understanding of the domain to be of use.
    + **Not** cross-domain, per definition.    

* [ESO Reflex](https://www.eso.org/sci/software/esoreflex/)
    + Based on [Kepler, which seems out of support](https://kepler-project.org/users/downloads.html), standalone tools for reducing VLT (Very Large Telescope)/VLTI (Very Large Telescope Interferometer) science data. Part of the [VLT Instrument Pipelines](https://www.eso.org/sci/software/pipelines/)
    + Standalone, no container-based installation.

## Humanities

* [TAPAS (TEI Archiving, Publishing, and Access Service), a platform for archiving and publishing TEI (Text Encoding Initiative) documents.](http://www.tapasproject.org)
    + Online only.
    + Uses the [Text Encoding Initiative XML format (TEI)](https://tei-c.org/release/doc/tei-p5-doc/en/html/index.html)
    + No easily findable API
    + Interoperability **LOW/MEDIUM**: despite the lack of API, each element is findable online and is composed of a well-documented XML and images.
    + **Not** cross-domain, as per definition.

* [Humanities Commons, a network for scholars to share work and connect, with the CORE repository](https://hcommons.org)
    + Online only.
    + No easily findable API
    + Interoperability **LOW**: it is a repository of documents that are in binary format (docx, pdf for instance), with only metadata in XML
    + **Not** cross-domain, as per definition.

* [Omeka, a content management system for digital collections and exhibitions](https://omeka.org)
    + No container-based installation, though it was dockerized previously.
    + 2 versions, Omeka S for sharable resource pool across multiple sites and Omeka Classic for individual projects.
    + [Extensive PHP API, more limited REST API, well documented](https://omeka.org/s/docs/developer/api/)
    + Interoperability **MEDIUM/HIGH**: uses JSON, seems to be lacking examples and/or samples. Offer a [DSpace connector](https://omeka.org/s/docs/user-manual/modules/dspaceconnector/) and [Zortero Import](https://omeka.org/s/docs/user-manual/modules/zoteroimport/)
    + **Fully** cross-domain: can be used for referencing any kind of digital resources.

* [Archaeology Data Service (ADS), for archiving digital data in archaeology.](https://archaeologydataservice.ac.uk)
    + Online only.
    + No API but a [harvesting interface using OAI-PMH](https://archaeologydataservice.ac.uk/about/policies/metadata/metadata-services/) and an (extensive documentation)[https://archaeologydataservice.ac.uk/help-guidance/], including on [data repositories citing the ADS, that might have an API](https://archaeologydataservice.ac.uk/help-guidance/data-reuse/fair-data/)
    + Interoperability **MEDIUM/HIGH**: uses standards (DOI, ORCID, Dublin Core) and very well documented. The documentation is also very accessible. Automatic access would need to be through harvesting or an external repository, making things a bit harder.
    + **Not** cross-domain, as per definition.

* [Europeana, providing access to cultural heritage data from European institutions](https://www.europeana.eu)
    + Online only.
    + There is an API, as shown with a footer link "See requests to Europeana APIs", but without any visible documentation.
    + Interoperability **LOW**: it is a repository of medias with a powerful search/filter, but without clear API.
    + **Not** cross-domain, as per definition.

## Bibliography

* ["Zotero is free and open-source reference management software to manage bibliographic data and related research materials"](https://www.zotero.org/)
    + Mostly online with browser's extension. It is a tool to help getting information from web-sites, organize and cite.
    + Many [extensions](https://www.zotero.org/support/plugins) providing some web API support.
    + Interoperability **HIGH**: again with many plugins but also [integrations](https://www.zotero.org/support/word_processor_integration).
    + By definition cross-domain: it is a tool to build and manage bibliographic data

## Generalists

All are inherently cross-platform and most follow the FAIR principle.

* [Open Science Framework (OSF), a platform that supports open research](https://osf.io)
    + Online
    + [Extensive API](https://developer.osf.io/)
    + Interoperability **HIGH**: uses well-documented JSON.

* [RDMO - Research Data Management Organiser](https://rdmorganiser.github.io/en/)
    + [Docker Compose](https://github.com/rdmorganiser/rdmo-docker-compose)
    + [Extensive API](https://rdmo.readthedocs.io/en/latest/administration/api.html)
    + Interoperability **HIGH**: uses well-documented JSON.

* [The Comprehensive Knowledge Archive Network (CKAN) is an open-source open data portal for the storage and distribution of open data (wikipedia)](https://ckan.org/)
    + [Docker Compose](https://docs.ckan.org/en/2.11/maintaining/installing/index.html)
    + [API](https://docs.ckan.org/en/2.11/api/index.html)
    + Interoperability **MEDIUM**: the API is not documented fully.

* [Dataverse, an open source research data repository software](https://dataverse.org/)
    + [Docker Compose and Kubernetes](https://guides.dataverse.org/en/latest/developers/containers.html)
    + [Extensive API](https://guides.dataverse.org/en/latest/api/index.html)
    + Interoperability **HIGH**: uses documented JSON.

* ["Zenodo is a general-purpose open repository developed under the European OpenAIRE program and operated by CERN"](https://zenodo.org/)
    + Mostly used online, but provide a [Docker Compose](https://github.com/zenodo/zenodo-rdm)
    + [Extensive API](https://developers.zenodo.org/)
    + Interoperability **HIGH**: uses well-documented JSON.

* [BARTOC is a register of Thesauri, Ontologies & Classifications](https://bartoc.org/)
    + [Docker and docker-compose installation supported but mostly supposed to be used online as a register](https://github.com/gbv/bartoc.org/blob/main/docker/README.md)
    + [Extensive API](https://bartoc.org/vocabularies?search=BARTOC)
    + Interoperability **HIGH**: uses well-documented JSON.

* [RDM, turn-key research data management repository](https://inveniordm.docs.cern.ch/)
    + [Docker image](https://inveniordm.docs.cern.ch/maintenance/docker-images/)
    + [Extensive API](https://inveniordm.docs.cern.ch/reference/rest_api_index/)
    + Interoperability **HIGH**: uses well-documented JSON.

* [INVENIO, a framework for large-scale digital repositories](https://invenio.readthedocs.io/en/latest/)
    + Framework to develop repositories, such as RDM
    + [API](https://invenio-records-rest.readthedocs.io/en/latest/)
    + Interoperability **HIGH**: All documented, used to build other repositories.

* [RODARE, ROssendorf DAta REpository, Online Data Repository](https://rodare.hzdr.de/about/)
    + Based on INVENIO Digital Library framework, fork of Zenodo.
    + Explain [how it is FAIR](https://rodare.hzdr.de/about/principles/)
    + [Extensive API, per community](https://rodare.hzdr.de/communities/)
    + Interoperability **MEDIUM/HIGH**: It lacks a simple API documentation.

* [REANA, Reproducible and reusable research data analysis platform](https://reanahub.io/)
    + [Kubernetes, Helm and Kubernetes in Docker](https://docs.reana.io/administration/)
    + [Extensive APIs](https://docs.reana.io/reference/)
    + Interoperability **HIGH**: use a yaml file which is [fully documented](https://docs.reana.io/reference/reana-yaml/)

* [UNICORE, A European Federation Software Suite](https://www.unicore.eu/)
    + [Docker image but mostly for evaluation](https://unicore-docs.readthedocs.io/en/latest/gettingstarted.html?highlight=docker#evaluating-unicore)
    + [Extensive API](https://unicore-docs.readthedocs.io/en/latest/user-docs/rest-api/index.html)
    + Interoperability **HIGH**: uses well-documented JSON.

* [SciCat, management and annotation of scientific data based on Elastic Search](https://scicatproject.github.io/)
    + [Default docker-compose installation](https://scicatproject.github.io/scicatlive/latest/)
    + [Extensive API](https://scicatproject.github.io/api-documentation/)
    + Interoperability **HIGH**: uses well-documented JSON.

* [re3data, registry of research data repositories](https://www.re3data.org/)
    + Online.
    + [Extensive API](https://www.re3data.org/api/doc)
    + Interoperability **HIGH**: uses XML following a given schema.

* [udata, social platform dedicated to open data](https://github.com/opendatateam/udata)
    +  [Docker compose and docker images](https://udata.readthedocs.io/en/stable/docker-deployment/)
    + [Extensive API using RDF](https://udata.readthedocs.io/en/stable/rdf/)
    + Interoperability **HIGH**: Return RDF following the [Data Catalog Vocabulary](https://www.w3.org/TR/vocab-dcat/).

* [DSpace, Open Digital Repository](https://dspace.org/)
    + [Docker install, but not recommended for production](https://wiki.lyrasis.org/display/DSPACE/Try+out+DSpace+8)
    + [Extensive API](https://github.com/DSpace/DSpace/releases/tag/dspace-8.0), full part of the back-end, [well-documented](https://github.com/DSpace/RestContract?tab=readme-ov-file#rest-endpoints)
    + Interoperability **HIGH**: uses well-documented JSON.

* [Dryad, Open Source Publishing Platform](https://datadryad.org/)
    + Only online.
    + [Extensive API, well documented](https://datadryad.org/stash/api)
    + Interoperability **HIGH**: uses well-documented JSON.

* [Elsevier Data Repository](https://elsevier.digitalcommonsdata.com/research-data/)
    + Online, with a possibility for a [commercial local setup](https://www.elsevier.com/products/digital-commons/data).
    + [Extensive API, well documented](https://elsevier.digitalcommonsdata.com/api/docs/).
    + Interoperability **HIGH**: uses well-documented JSON.

* [Figshare, Research Repository](https://figshare.com/)
    + Only Online, with free access for non-profit research.
    + [Extensive API, well documented](https://help.figshare.com/article/how-to-use-the-figshare-api) and [integrations](https://knowledge.figshare.com/app-category/integrations).
    + Interoperability **HIGH**: uses well-documented JSON and mamy examples, also in several programming languages.

* [NextFlow, using software containers for scientific workflow](https://www.nextflow.io/)
    + [Docker image](https://hub.docker.com/r/nextflow/nextflow)
    + [Externally developed API, documented](https://github.com/SciDAS/nextflow-api)
    + Interoperability **LOW/MEDIUM**: aside the external API and some standard storage options, such as AWS, there is no clear way to use NextFlow programmatically

## Authority control

* [ORCID, Open Researcher and Contributor ID](https://orcid.org/)
    + Online.
    + [Extensive API](https://info.orcid.org/documentation/api-tutorials/api-tutorial-read-data-on-a-record/)
    + Interoperability **HIGH**: provide a [defined model with XSD](https://github.com/ORCID/orcid-model)
    + **Fully** cross-domains

* [ROR, "a global, community-led registry of open persistent identifiers for research organizations"](https://ror.org/)
    + Online
    + [Extensive API](https://ror.readme.io/docs/rest-api)
    + Interoperability **HIGH**: uses well-documented JSON and the metadata is [fully documented](https://ror.readme.io/docs/updates)
    + **Fully** cross-domains

* [DOI, Digital Object Identifier](https://www.doi.org/)
    + No need for API: the DOI reference the object
    + Interoperability **HIGH**: Fully [documented](https://www.doi.org/the-identifier/what-is-a-doi/)
    + **Fully** cross-domains

* [ISSN, International Identifier for serials](https://www.issn.org/)
    + No need for API: An ID for serial publications, such as journals, magazines. 
    + Lookup available and other services available, API for lookup is [not free](https://portal.issn.org/services). Other tools have free API, well documented.
    + Interoperability **HIGH**: Fully [documented](https://www.issn.org/understanding-the-issn/what-is-an-issn/)
    + **Fully** cross-domains

* [ISBN,  International Standard Book Number](https://www.isbn-international.org/)
    + No need for API: An ID for books. Lookups are available but not part of the ISBN.
        - One lookup service is [ISBNDB](https://isbndb.com/), with a [well documented API](https://isbndb.com/apidocs/v2)
    + Interoperability **HIGH**: Fully [documented](https://www.isbn-international.org/content/isbn-users-manual/29)
    + **Fully** cross-domain

* [VIAF, Virtual International Authority File](https://viaf.org/)
    + Online
    + No API or not documented.
    + Interoperability **LOW**: not documented or documentation hard to find.
    + **Fully** cross-domain.

* [GeoNames, database of placenames](https://www.geonames.org/)
    + Online, not open-source. Data is under CC-BY licence.
    + [Expensive APIs, well documented](https://www.geonames.org/export/web-services.html), also with many [client libraries](https://www.geonames.org/export/client-libraries.html)
    + Interoperability **HIGH**: all data formats are well documented.
    + **Not** cross-domain **but** can be used for any need of geographic data.

## Others

* [NextCloud](https://nextcloud.com/)
    + NextCloud is a file hosting service, similar to Google Drive or Microsoft OneDrive, but OpenSource that can be self-hosted. It is a free file hosting platform, it does not constraint which data are stored and do not follow complex metadata or formats. It can be extended and adapted using plugins, such as a plugin to integrate an office suite, such as LibreOffice.
    As such, it should be considered a support application before all: a tool to support your work, or a way to store data for other applications. The absence of constraint makes it a poor choice for FAIR data storage, as the users would need to do most of the needed work. Still, interconnected via API to other Software, it could be an essential part of a Data Management solution, even if only as a scrapbook.
    NextCloud has an extensive API, so could be used with constraint via the API using a dedicated Pipeline. It could be with connection with another application or for a specific use-case.
    + [Docker](https://docs.nextcloud.com/server/latest/admin_manual/office/example-docker.html), [Docker compose](https://github.com/nextcloud/all-in-one/blob/main/manual-install/latest.yml) and Kubernetes installation, with [Helm chart](https://github.com/nextcloud/helm) 
    + [Extensive API](https://docs.nextcloud.com/server/latest/developer_manual/client_apis/general.html)
    + Interoperability **HIGH**: The API is well documented and there is several ways of doing things. Then NextCloud is highly flexible, so the use will need to be defined clearly and there might need to restrict it using the API for uploads in order to integrate it in an assembly.
    + Fully cross-domain
